// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVr2EH0_kaJIs5p_M0iQZsly-q_YK1Y8',
    appId: '1:519364797751:web:ad992ad0d4bcae6c6566b2',
    messagingSenderId: '519364797751',
    projectId: 'balance-baller',
    authDomain: 'balance-baller.firebaseapp.com',
    storageBucket: 'balance-baller.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Xh5MxxKteHcSRS6ZE3Xp1qdTHBye6Qc',
    appId: '1:519364797751:android:7254a10f54f41e136566b2',
    messagingSenderId: '519364797751',
    projectId: 'balance-baller',
    storageBucket: 'balance-baller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBae4-ZelzKeNFy-rAeqee0a3K-iLFG00',
    appId: '1:519364797751:ios:2cc97c602d0d2e966566b2',
    messagingSenderId: '519364797751',
    projectId: 'balance-baller',
    storageBucket: 'balance-baller.appspot.com',
    iosBundleId: 'com.balanceballers.balanceballers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBae4-ZelzKeNFy-rAeqee0a3K-iLFG00',
    appId: '1:519364797751:ios:1754f596434528bb6566b2',
    messagingSenderId: '519364797751',
    projectId: 'balance-baller',
    storageBucket: 'balance-baller.appspot.com',
    iosBundleId: 'com.balanceballers.balanceballers.RunnerTests',
  );
}
